### ISSUE TITLE
Need more alarm types

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/schemas#53] opened 2019-09-04 16:53 UTC
Currently there is only one type of alarm.

Some devices contain multiple alarms. For example, it is quite common to have a combined Smoker/Carbon Monoxide alarms.

As a user I should be able to choose if I want it to display primarily as a Smoke Detector or as a Carbon Monoxide Detector.

**Comment by mrstegeman** [comment] 2019-09-04 16:53
Duplicate of #38 and #39

**Closed by mrstegeman** 2019-09-04 16:53 UTC
